### ISSUE TITLE
clang 14+15: update and inspect results for disabled tests

### ISSUE THREAD

**Issue by lzaoral** [aufover/aufover-benchmark#32]
Some of the `single-c` test were disabled as `clang` reported either nothing or a false positive.  That was with `clang` 10 (if I recall correctly) and it might be quite interesting to see how `clang` 14 improved.

**Comment by vmihalko** [comment]
How to resolve this issue? Run: 
```console
$ ./test/single-c/sync.sh -L clang
```
and inspect (`git status`) new files...

**Comment by psimovec** [comment]
Clang has some output in tests/single-c/mem-basic-realloc  

- 0032-0037 clang gets TP right, I should add these test cases
- 0063 to 0067 false positives, seems to not understand errno 
- 0076-0079 FP, does not understand errno again, FN - misses the real problem 
- 0080-0083 the same FP as in previous tests, but this time clang gets the TP right
